name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Update JS file with current date and time
        run: |
          sed -i "s/Last update : .*/Last update : $(date)/" youtube.user-auto.js

      - name: Commit changes
        run: |
          git add .
          git commit -m "Daily update: $(date)"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true # Use with caution!  Consider removing this.
