name: Daily Commit Manual

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create file if it doesn't exist
        uses: actions/github-script@v6
        if: "!contains(github.event_name, 'push')"
        with:
          script: |
            const fs = require('fs');
            if (!fs.existsSync('youtube.user-auto.js')) {
              fs.writeFileSync('youtube.user-auto.js', `// Last update : ${new Date().toISOString()}\n`);
              console.log('File youtube.user-auto.js created.');
            }

      - name: Update JS file with current date and time
        run: |
          sed -i "s/Last update : .*/Last update : $(date)/" youtube.user-auto.js || { echo "sed command failed" >&2; exit 1; }

      - name: Add changes
        run: git add . || { echo "git add failed" >&2; exit 1; }

      - name: Commit changes
        run: |
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Daily update: $(date)" || { echo "git commit failed" >&2; exit 1; }
          else
            echo "No changes to commit." >&2
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN_WRITE }}
          branch: main
        if: success()
